---
# file: roles/nginx/tasks/main.yml

- name: install nginx rpm from a remote repo
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: install nginx
  yum: name=nginx state=present

- name: enable nginx
  service: name=nginx enabled=yes

- name: copy default.conf
  copy: dest=/etc/nginx/conf.d/default.conf src=default.conf

- name: start nginx
  service: name=nginx state=started


